# Site settings
title: Kevin Rocker's Static Depo.
email: kevin.j.rocker@gmail.com
description: ""
baseurl: ""
url: "http://www.kevinrocker.co"
github_username:  krocker34

# Build settings
markdown: kramdown
permalink: pretty
gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
